
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ModernEstate.BLL.InvoiceDocuments
{
    public class InvoiceDocument : IDocument
    {
        public string InvoiceNumber { get; }
        public DateTime Date { get; }
        public IReadOnlyList<(string Item, int Qty, decimal Price)> Lines { get; }

        public InvoiceDocument(string invoiceNumber, DateTime date, IReadOnlyList<(string, int, decimal)> lines)
        {
            InvoiceNumber = invoiceNumber;
            Date = date;
            Lines = lines;
        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

        public void Compose(IDocumentContainer container)
        {
            container
               .Page(page =>
               {
                   page.Margin(50);
                   page.Header().Text($"Hóa đơn #{InvoiceNumber}").FontSize(20).Bold();
                   page.Content().Column(col =>
                   {
                       col.Item().Text($"Ngày: {Date:dd/MM/yyyy}");
                       col.Item().Table(table =>
                       {
                           // header
                           table.ColumnsDefinition(columns =>
                           {
                               columns.RelativeColumn();
                               columns.ConstantColumn(50);
                               columns.ConstantColumn(80);
                           });

                           table.Header(header =>
                           {
                               header.Cell().Text("Mục hàng").Bold();
                               header.Cell().Text("SL").Bold();
                               header.Cell().Text("Giá").Bold();
                           });

                           // data rows
                           foreach (var line in Lines)
                           {
                               table.Cell().Text(line.Item);
                               table.Cell().Text(line.Qty);
                               table.Cell().Text($"{line.Price:C}");
                           }
                       });
                   });
                   page.Footer().AlignCenter().Text(x =>
                   {
                       x.Span("Generated by ASP.NET 8 – ").FontSize(10);
                       x.Span(DateTime.Now.ToString("dd/MM/yyyy HH:mm")).FontSize(10);
                   });
               });
        }
    }
}