version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnectionString=Server=mysql;Port=3306;User Id=root;Password=Nghia_2003;Database=db_local_ModernEstate;SslMode=Required;
    depends_on:
      - mysql
    networks:
      - modernestate-network

  mysql:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Nghia_2003
      - MYSQL_DATABASE=db_local_ModernEstate
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - modernestate-network

networks:
  modernestate-network:
    driver: bridge

volumes:
  mysql-data: 