version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=modernestate
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: nghiatlm/modernestate-backend:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=modernestate
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    # volumes:
    #   - ~/.aspnet/https:/https:ro
volumes:
  mysql_data:

    # docker-compose -p modernstate up -d
